---
title: infoscape
hostname: news.ksar.dev
keywords:
- Yandex
- Яндекс
- Moscow
- Москва
- Group-IB
- Google
- Гугл
sources:

- title: 42 секунды
  id: ftsec
  parser: telegram
  link: https://t.me/s/ftsec
  pages:
  - fast
- title: Москва 24
  id: infomoscow24
  parser: telegram
  link: https://t.me/s/infomoscow24
  pages:
  - fast
- title: The Bell
  id: thebell_io
  parser: telegram
  link: https://t.me/s/thebell_io
  pages:
  - fast

- title: БизнесФМ
  id: bfmnews
  parser: telegram
  link: https://t.me/s/bfmnews
  pages:
  - fast
- title: РИА
  id: rian_ru
  parser: telegram
  link: https://t.me/s/rian_ru
  pages:
  - fast
- title: Рыбарь
  id: rybar
  parser: telegram
  link: https://t.me/s/rybar
  pages:
  - fast

- title: На марше Z
  id: namarshe
  parser: telegram
  link: https://t.me/s/namarshe
  pages:
  - fast
- title: Резидент
  id: rezident_ua
  parser: telegram
  link: https://t.me/s/rezident_ua
  pages:
  - fast
- title: Легитимный
  id: legitimniy
  parser: telegram
  link: https://t.me/s/legitimniy
  pages:
  - fast

- title: addmeto
  id: addmeto
  parser: telegram
  link: https://t.me/s/addmeto
  pages:
  - tech
- title: Daily Geek News
  id: daily_geek_news
  parser: telegram
  link: https://t.me/s/daily_geek_news
  pages:
  - tech
- title: opennet.ru
  id: opennet_ru
  parser: telegram
  link: https://t.me/s/opennet_ru
  pages:
  - tech

- title: Linux.org.ru
  id: best_of_lor
  parser: telegram
  link: https://t.me/s/best_of_lor
  pages:
  - tech
- title: БлоGнот
  id: blognot
  parser: telegram
  link: https://t.me/s/blognot
  pages:
  - tech
- title: Стартап дня. Александр Горный.
  id: startupoftheday
  parser: telegram
  link: https://t.me/s/startupoftheday
  pages:
  - tech
