version: "3.4"
services:
  infoscape:
    build: .
    container_name: infoscape
    restart: always
    volumes:
      - infoscape-data:/data
    environment:
     - AUTH_SECRET=<random_string>
     - TG_TOKEN=<telegram_token>
volumes:
  infoscape-data:
