version: "3.4"
services:
  infoscape:
    build: .
    container_name: infoscape
    restart: always
    volumes:
      - infoscape-data:/data
    environment:
     - AUTH_SECRET=secret
volumes:
  infoscape-data:
